// console.log('hi');


// const number = 122323;
// let MailOfThePerson = 'thisisash@gmail.com'
// var accountCity ="Ambala"

// arya = 3434;


// const number = 324324;
// console.log(number);

// // alert("hello")

// console.log(typeof null);
// console.log(typeof undefined);


// let score = 23;
// let score = 23;

// // console.log(typeof score);

// let ThisScoreInString = String(score)
// console.log(typeof score);
// console.log(typeof ThisScoreInString);
// console.log(ThisScoreInString);

// // NaN= NOT A Number
// // console.log(typeof NaN);


// let Papi = ' '
// let PapiPI = Boolean(Papi)
// console.log(Papi);
// console.log(PapiPI);

// let value = 3;
// let negValue = -value;

// console.log(negValue);

// let str1 ="hello"
// let str2 = " diddy"
// let str3 = str1+str2
// console.log(str3);



// console.log("1" + 2);
// console.log("1" + 3+ 2); //output 132
// console.log(1 + 3+ "3"); //output 42

// console.log(+true);//output will be 1
// console.log(+" ");


// let n1,n2,n3;
// n1 = n2 = n3 = 2+2

// console.log(n1,n2,n3);


// let gameCounter = 100;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// ++gameCounter;
// console.log(gameCounter);



// console.log("2" > 1);
// console.log("09" > 1);

// console.log(null >  0);
// console.log(null == 0);
// console.log(null >= 0);

// console.log(undefined == 0);
// console.log(undefined > 0);
// console.log(undefined < 0);

// console.log("2" == 2);
// console.log("2" === 2);

// const id = Symbol('123')
// // console.log(id);
// console.log(typeof Symbol());
// console.log(typeof Symbol);



// const bigNumber = 555656846546n
// console.log(typeof bigNumber);


// const papi = ["papi1", "diddy", "bubu"]
// // console.log(papi);

// let blowbj = {
//     name:"ash_pipi",
//     age:54,
// }

// console.log(typeof blowbj);


// const ThisIsFunction = function(){
//     console.log("papi");
    
// }
// const ThisIsFunction = ()=>{
//     console.log("papi");
    
// }

// ThisIsFunction()


// let myDate = new Date()
// console.log(myDate);

// console.log(myDate.toString());
// console.log(myDate.toDateString());
// console.log(myDate.toISOString());
// console.log(myDate.toLocaleString());
// console.log(myDate.toTimeString());
// console.log(typeof myDate);

let myCreatedDate = new Date(2025,2,23)
// let myCreatedDate2 = new Date('2025-3-23')
// console.log(myCreatedDate);

let Time = Date.now()

console.log(Time);

console.log(myCreatedDate.getTime());
console.log(Math.floor(Date.now()/1000))

// const score = 78;
// let arya = String(score)

